import { useState } from 'react';
import { formatCurrency, calculateExpenseSplit } from '../utils/splitCalculator';
import { TRIP_INFO } from '../data/initialData';
import './SettlementView.css';

function SettlementView({ friends, balances, settlements, payments = [], expenses = [], stats = {}, categories = [], onRecordPayment, onDeletePayment }) {
    const [showCopied, setShowCopied] = useState(false);

    const getFriendInfo = (friendId) => friends.find(f => f.id === friendId) || {};
    const getCategoryInfo = (categoryId) => categories.find(c => c.id === categoryId) || { icon: '📦', name: 'Other' };

    // Separate creditors and debtors for balance overview
    const creditors = friends.filter(f => balances[f.id] > 0.01);
    const debtors = friends.filter(f => balances[f.id] < -0.01);
    const settled = friends.filter(f => Math.abs(balances[f.id]) <= 0.01);

    // Sort payments by date (newest first)
    const sortedPayments = [...payments].sort((a, b) => b.createdAt - a.createdAt);

    // Sort expenses by date (newest first)
    const sortedExpenses = [...expenses].sort((a, b) => b.createdAt - a.createdAt);

    // Calculate per-person spending (how much each person's share was)
    const getPersonSpending = () => {
        const spending = {};
        friends.forEach(f => { spending[f.id] = 0; });

        expenses.forEach(expense => {
            const splits = calculateExpenseSplit(expense, friends);
            Object.entries(splits).forEach(([friendId, amount]) => {
                spending[friendId] = (spending[friendId] || 0) + amount;
            });
        });

        return spending;
    };

    const personSpending = getPersonSpending();

    // Generate shareable text summary
    const generateShareText = () => {
        let text = `🏝️ *${TRIP_INFO.name}*\n`;
        text += `📍 ${TRIP_INFO.location} • ${TRIP_INFO.dates || `${TRIP_INFO.startDate} to ${TRIP_INFO.endDate}`}\n\n`;

        // Trip Overview
        text += `📊 *Trip Overview*\n`;
        text += `• Total Spent: ₹${Math.round(stats.totalSpent || 0).toLocaleString('en-IN')}\n`;
        text += `• Total Expenses: ${stats.expenseCount || 0}\n`;
        text += `• Per Person Avg: ₹${Math.round((stats.totalSpent || 0) / friends.length).toLocaleString('en-IN')}\n\n`;

        // Who Paid What
        text += `💳 *Who Paid What*\n`;
        friends.forEach(friend => {
            const paid = stats.paidByPerson?.[friend.id] || 0;
            if (paid > 0) {
                text += `• ${friend.name}: ₹${Math.round(paid).toLocaleString('en-IN')}\n`;
            }
        });
        text += `\n`;

        // Per Person Spending (their share)
        text += `🍽️ *Per Person Spending*\n`;
        friends.forEach(friend => {
            const spent = personSpending[friend.id] || 0;
            text += `• ${friend.name}: ₹${Math.round(spent).toLocaleString('en-IN')}\n`;
        });
        text += `\n`;

        // All Expenses
        if (expenses.length > 0) {
            text += `🧾 *All Expenses*\n`;
            sortedExpenses.forEach(exp => {
                const payer = getFriendInfo(exp.paidBy);
                const cat = getCategoryInfo(exp.category);
                text += `• ${cat.icon} ${exp.description}: ₹${Math.round(exp.amount).toLocaleString('en-IN')} (paid by ${payer.name})\n`;
            });
            text += `\n`;
        }

        // Category Breakdown
        if (stats.byCategory && Object.keys(stats.byCategory).length > 0) {
            text += `📈 *By Category*\n`;
            categories.forEach(cat => {
                const amount = stats.byCategory[cat.id] || 0;
                if (amount > 0) {
                    text += `• ${cat.icon} ${cat.name}: ₹${Math.round(amount).toLocaleString('en-IN')}\n`;
                }
            });
            text += `\n`;
        }

        // Settlements
        if (settlements.length === 0) {
            text += `🎉 All settled up! No pending payments.\n`;
        } else {
            text += `💸 *Settlements Required*\n`;
            settlements.forEach(t => {
                const from = getFriendInfo(t.from);
                const to = getFriendInfo(t.to);
                text += `• ${from.name} ➜ ${to.name}: ₹${Math.round(t.amount).toLocaleString('en-IN')}\n`;
            });
        }

        if (payments.length > 0) {
            text += `\n✅ *Payments Made*\n`;
            payments.forEach(p => {
                const from = getFriendInfo(p.from);
                const to = getFriendInfo(p.to);
                text += `• ${from.name} paid ${to.name}: ₹${Math.round(p.amount).toLocaleString('en-IN')}\n`;
            });
        }

        text += `\n_Generated by Split It_`;
        return text;
    };

    // Copy to clipboard
    const handleCopyToClipboard = async () => {
        const text = generateShareText();
        try {
            await navigator.clipboard.writeText(text);
            setShowCopied(true);
            setTimeout(() => setShowCopied(false), 2000);
        } catch (err) {
            console.error('Failed to copy:', err);
        }
    };

    // Share via WhatsApp
    const handleWhatsAppShare = () => {
        const text = generateShareText();
        const encodedText = encodeURIComponent(text);
        window.open(`https://wa.me/?text=${encodedText}`, '_blank');
    };

    // Native share (mobile)
    const handleNativeShare = async () => {
        const text = generateShareText();
        if (navigator.share) {
            try {
                await navigator.share({
                    title: TRIP_INFO.name,
                    text: text
                });
            } catch (err) {
                // User cancelled or error
                console.log('Share cancelled');
            }
        } else {
            handleCopyToClipboard();
        }
    };

    return (
        <div className="settlement-view">
            {/* Balance Overview */}
            <section className="section">
                <h2 className="section-title">Balance Overview</h2>
                <p className="section-subtitle">See who's owed and who owes money</p>

                <div className="balance-overview">
                    {/* Gets Back */}
                    <div className="balance-column positive">
                        <div className="column-header">
                            <span className="column-icon">💚</span>
                            <h3>Gets Back</h3>
                        </div>
                        {creditors.length === 0 ? (
                            <p className="no-items">No one is owed money</p>
                        ) : (
                            <>
                                {creditors.map(friend => (
                                    <div key={friend.id} className="balance-row">
                                        <div className={`avatar ${friend.color}`}>
                                            {friend.name.charAt(0)}
                                        </div>
                                        <span className="balance-name">{friend.name}</span>
                                        <span className="amount amount-positive">
                                            +{formatCurrency(balances[friend.id])}
                                        </span>
                                    </div>
                                ))}
                            </>
                        )}
                    </div>

                    {/* Owes */}
                    <div className="balance-column negative">
                        <div className="column-header">
                            <span className="column-icon">❤️</span>
                            <h3>Owes</h3>
                        </div>
                        {debtors.length === 0 ? (
                            <p className="no-items">No one owes money</p>
                        ) : (
                            <>
                                {debtors.map(friend => (
                                    <div key={friend.id} className="balance-row">
                                        <div className={`avatar ${friend.color}`}>
                                            {friend.name.charAt(0)}
                                        </div>
                                        <span className="balance-name">{friend.name}</span>
                                        <span className="amount amount-negative">
                                            {formatCurrency(balances[friend.id])}
                                        </span>
                                    </div>
                                ))}
                            </>
                        )}
                    </div>
                </div>

                {settled.length > 0 && (
                    <div className="settled-row">
                        <span className="settled-icon">✅</span>
                        <span>
                            {settled.map(f => f.name).join(', ')} {settled.length === 1 ? 'is' : 'are'} already settled up!
                        </span>
                    </div>
                )}
            </section>

            {/* Trip Summary Section */}
            <section className="section trip-summary-section">
                <h2 className="section-title">📋 Trip Summary</h2>
                <p className="section-subtitle">Complete breakdown of all expenses and spending</p>

                {/* Quick Stats */}
                <div className="summary-stats-row">
                    <div className="summary-stat-card">
                        <span className="summary-stat-icon">💰</span>
                        <div className="summary-stat-content">
                            <span className="summary-stat-value">{formatCurrency(stats.totalSpent || 0)}</span>
                            <span className="summary-stat-label">Total Spent</span>
                        </div>
                    </div>
                    <div className="summary-stat-card">
                        <span className="summary-stat-icon">📝</span>
                        <div className="summary-stat-content">
                            <span className="summary-stat-value">{stats.expenseCount || 0}</span>
                            <span className="summary-stat-label">Expenses</span>
                        </div>
                    </div>
                    <div className="summary-stat-card">
                        <span className="summary-stat-icon">👥</span>
                        <div className="summary-stat-content">
                            <span className="summary-stat-value">{formatCurrency((stats.totalSpent || 0) / friends.length)}</span>
                            <span className="summary-stat-label">Avg Per Person</span>
                        </div>
                    </div>
                </div>

                {/* Per Person Breakdown */}
                <div className="person-breakdown">
                    <h3 className="subsection-title">💳 Per Person Breakdown</h3>
                    <div className="person-breakdown-grid">
                        {friends.map(friend => {
                            const paid = stats.paidByPerson?.[friend.id] || 0;
                            const spent = personSpending[friend.id] || 0;
                            const diff = paid - spent;

                            return (
                                <div key={friend.id} className="person-card">
                                    <div className="person-card-header">
                                        <div className={`avatar ${friend.color}`}>
                                            {friend.name.charAt(0)}
                                        </div>
                                        <span className="person-name">{friend.name}</span>
                                    </div>
                                    <div className="person-card-stats">
                                        <div className="person-stat">
                                            <span className="person-stat-label">Paid</span>
                                            <span className="person-stat-value paid">{formatCurrency(paid)}</span>
                                        </div>
                                        <div className="person-stat">
                                            <span className="person-stat-label">Spent</span>
                                            <span className="person-stat-value spent">{formatCurrency(spent)}</span>
                                        </div>
                                        <div className="person-stat diff">
                                            <span className="person-stat-label">Balance</span>
                                            <span className={`person-stat-value ${diff >= 0 ? 'positive' : 'negative'}`}>
                                                {diff >= 0 ? '+' : ''}{formatCurrency(diff)}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </div>

                {/* Category Breakdown */}
                {stats.byCategory && Object.keys(stats.byCategory).length > 0 && (
                    <div className="category-breakdown">
                        <h3 className="subsection-title">📈 By Category</h3>
                        <div className="category-pills">
                            {categories.map(cat => {
                                const amount = stats.byCategory[cat.id] || 0;
                                if (amount <= 0) return null;
                                const percentage = ((amount / stats.totalSpent) * 100).toFixed(0);
                                return (
                                    <div key={cat.id} className="category-pill" style={{ borderColor: cat.color }}>
                                        <span className="category-pill-icon">{cat.icon}</span>
                                        <div className="category-pill-info">
                                            <span className="category-pill-name">{cat.name}</span>
                                            <span className="category-pill-amount">{formatCurrency(amount)} ({percentage}%)</span>
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                )}

                {/* All Expenses List */}
                {expenses.length > 0 && (
                    <div className="all-expenses">
                        <h3 className="subsection-title">🧾 All Transactions ({expenses.length})</h3>
                        <div className="expenses-list">
                            {sortedExpenses.map((expense, index) => {
                                const payer = getFriendInfo(expense.paidBy);
                                const cat = getCategoryInfo(expense.category);

                                return (
                                    <div
                                        key={expense.id}
                                        className="expense-row"
                                        style={{ animationDelay: `${index * 0.03}s` }}
                                    >
                                        <div className="expense-row-left">
                                            <span className="expense-category-icon">{cat.icon}</span>
                                            <div className="expense-info">
                                                <span className="expense-description">{expense.description}</span>
                                                <span className="expense-meta">
                                                    <span className={`payer-badge ${payer.color}`}>
                                                        {payer.name} paid
                                                    </span>
                                                    <span className="expense-date">{expense.date}</span>
                                                </span>
                                            </div>
                                        </div>
                                        <span className="expense-amount">{formatCurrency(expense.amount)}</span>
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                )}
            </section>

            {/* Settlement Transactions */}
            <section className="section">
                <div className="section-header-row">
                    <div>
                        <h2 className="section-title">💸 Settle Up</h2>
                        <p className="section-subtitle">
                            {settlements.length === 0
                                ? 'Everyone is already settled!'
                                : `${settlements.length} transaction${settlements.length !== 1 ? 's' : ''} remaining`
                            }
                        </p>
                    </div>
                    <button className="btn btn-primary" onClick={onRecordPayment}>
                        + Record Payment
                    </button>
                </div>

                {settlements.length === 0 ? (
                    <div className="all-settled">
                        <div className="all-settled-icon">🎉</div>
                        <h3>All Settled Up!</h3>
                        <p>No one owes anyone money</p>
                    </div>
                ) : (
                    <div className="settlement-list">
                        {settlements.map((transaction, index) => {
                            const fromFriend = getFriendInfo(transaction.from);
                            const toFriend = getFriendInfo(transaction.to);

                            return (
                                <div
                                    key={index}
                                    className="settlement-card"
                                    style={{ animationDelay: `${index * 0.1}s` }}
                                >
                                    <div className="settlement-from">
                                        <div className={`avatar avatar-lg ${fromFriend.color}`}>
                                            {fromFriend.name?.charAt(0)}
                                        </div>
                                        <span className="settlement-name">{fromFriend.name}</span>
                                    </div>

                                    <div className="settlement-arrow">
                                        <span className="arrow-amount">{formatCurrency(transaction.amount)}</span>
                                        <div className="arrow-line">
                                            <div className="arrow-dot"></div>
                                            <div className="arrow-dash"></div>
                                            <div className="arrow-head">→</div>
                                        </div>
                                        <span className="arrow-label">pays</span>
                                    </div>

                                    <div className="settlement-to">
                                        <div className={`avatar avatar-lg ${toFriend.color}`}>
                                            {toFriend.name?.charAt(0)}
                                        </div>
                                        <span className="settlement-name">{toFriend.name}</span>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                )}
            </section>

            {/* Payment History */}
            {payments.length > 0 && (
                <section className="section">
                    <h2 className="section-title">📜 Payment History</h2>
                    <p className="section-subtitle">
                        {payments.length} payment{payments.length !== 1 ? 's' : ''} recorded
                    </p>

                    <div className="payment-history">
                        {sortedPayments.map((payment, index) => {
                            const fromFriend = getFriendInfo(payment.from);
                            const toFriend = getFriendInfo(payment.to);

                            return (
                                <div key={payment.id} className="payment-item" style={{ animationDelay: `${index * 0.05}s` }}>
                                    <div className="payment-info">
                                        <div className="payment-avatars">
                                            <div className={`avatar-small ${fromFriend.color}`}>
                                                {fromFriend.name?.charAt(0)}
                                            </div>
                                            <span className="payment-arrow-small">→</span>
                                            <div className={`avatar-small ${toFriend.color}`}>
                                                {toFriend.name?.charAt(0)}
                                            </div>
                                        </div>
                                        <div className="payment-details">
                                            <span className="payment-text">
                                                <strong>{fromFriend.name}</strong> paid <strong>{toFriend.name}</strong>
                                            </span>
                                            <span className="payment-meta">{payment.note} • {payment.date}</span>
                                        </div>
                                    </div>
                                    <div className="payment-amount-section">
                                        <span className="payment-amount">{formatCurrency(payment.amount)}</span>
                                        <button
                                            className="btn-icon btn-small btn-danger-icon"
                                            onClick={() => onDeletePayment(payment.id)}
                                            title="Delete payment"
                                        >
                                            🗑️
                                        </button>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </section>
            )}

            {/* Share Section */}
            <section className="section share-section">
                <h2 className="section-title">📤 Share Summary</h2>
                <p className="section-subtitle">Send the settlement details to your group</p>

                <div className="share-buttons">
                    <button className="btn btn-share btn-whatsapp" onClick={handleWhatsAppShare}>
                        <span className="share-icon">💬</span>
                        WhatsApp
                    </button>
                    <button className="btn btn-share btn-copy" onClick={handleCopyToClipboard}>
                        <span className="share-icon">📋</span>
                        Copy Text
                    </button>
                    <button className="btn btn-share btn-native" onClick={handleNativeShare}>
                        <span className="share-icon">📤</span>
                        Share
                    </button>
                </div>

                {/* Preview */}
                <div className="share-preview">
                    <div className="preview-header">
                        <span>Preview</span>
                    </div>
                    <pre className="preview-text">{generateShareText()}</pre>
                </div>
            </section>

            {/* Tips */}
            <div className="settlement-tips">
                <h4>💡 Quick Tips</h4>
                <ul>
                    <li>Use UPI or bank transfer for instant settlement</li>
                    <li>Record part payments to track progress</li>
                    <li>Share the summary to remind friends</li>
                </ul>
            </div>

            {/* Copied Toast */}
            {showCopied && (
                <div className="toast toast-success">
                    ✅ Copied to clipboard!
                </div>
            )}
        </div>
    );
}

export default SettlementView;
